[theme]
name = "nord-dark"
[theme.overrides]
separator = ""
#separator = "\ue0b2"
separator_bg = "#ff0000"
separator_fg = "auto"

[icons]
name = "awesome"


[[block]]
block = "music"
#player = "spotify"
buttons = ["play", "next"]

#[[block]]
#block = "bluetooth"
#mac = "E9:08:EF:8B:66:6C"
#format = "Boxen"
#format_unavailable = ""
#hide_disconnected = true

#[[block]]
#block = "bluetooth"
#mac = "28:11:A5:48:88:B4"
#format = "Bose"
#format_unavailable = ""
#hide_disconnected = true

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
full_format = "{percentage} " 
driver = "upower"
device= "DisplayDevice"


[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "tun[0-9]+"]
interface_name_include = []
ap_format = "{ssid^10}"
#device_format = "{ap} {ips}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 60
format = "%F %R"
